# name: application.yml
server:
  error:
    include-stacktrace: ON_PARAM
spring:
  datasource:
    url: jdbc:mysql://localhost:3309/spring_boot?useSSL=false&createDataBaseIfNotExists=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update